name: proteusAI
channels:
  - anaconda
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - cpuonly
  - pytorch
  - pytorch-scatter
  - pip
  - pip:
    - -e .[docs] -f https://data.pyg.org/whl/torch-2.3.0+cpu.html