name: proteusAI_depl

channels: 
   - pytorch
   - conda-forge
   - anaconda
   - pypi
   - pyg

dependencies:
 - torchvision
 - torchaudio
 - python=3.8
 - pandas
 - numpy
 - matplotlib 
 - scikit-learn
 - biopython
 - biotite
 - jupyter
 - jupyterlab
 - shiny
 #- pytorch::pytorch
 - pyg
 - torch-scatter
 - pytorch_scatter
 - openmm
 - pdbfixer
 - py3dmol
 - uvicorn
 - asgiref
 - starlette
 - requests
 - scipy
 - optuna
 - seaborn
 - openpyxl
 - gpytorch
 - umap-learn
 - pip 
 - pip:
    - fair-esm